_target_: src.model.LightCNN
conv_blocks:
  - { in_channels: 1, out_channels: 64,  kernel_size: 5, stride: 1, padding: 2, use_batchnorm: False }
  - { in_channels: 32, out_channels: 64,  kernel_size: 1, stride: 1, padding: 0, use_batchnorm: True }
  - { in_channels: 32, out_channels: 96,  kernel_size: 3, stride: 1, padding: 1, use_batchnorm: False }
  - { in_channels: 48, out_channels: 96,  kernel_size: 1, stride: 1, padding: 0, use_batchnorm: True }
  - { in_channels: 48, out_channels: 128, kernel_size: 3, stride: 1, padding: 1, use_batchnorm: False }
  - { in_channels: 64, out_channels: 128, kernel_size: 1, stride: 1, padding: 0, use_batchnorm: True }
  - { in_channels: 64, out_channels: 64,  kernel_size: 3, stride: 1, padding: 1, use_batchnorm: True }
  - { in_channels: 32, out_channels: 64,  kernel_size: 1, stride: 1, padding: 0, use_batchnorm: True }
  - { in_channels: 32, out_channels: 64,  kernel_size: 3, stride: 1, padding: 1, use_batchnorm: False }
max_pooling_conf:
    kernel_size: 2
    stride: 2
mlp1_conf:
    in_features: 62752
    out_features: 160
    use_batchnorm: True
mlp2_conf:
    in_features: 80
    out_features: 2
